services:
  postgres:
    image: postgres:16-alpine
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: